name: Build validation

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Test build website
        run: npm run build
